### ISSUE TITLE
Error code: NoAuthProvider

### ISSUE THREAD

**Issue by adminewacc** [abdtriedcoding/notesGPT#1]
Error: {"code":"NoAuthProvider","message":"No auth provider found matching the given token"}
    at m.query (/var/task/.next/server/chunks/493.js:1:3990)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async w (/var/task/.next/server/chunks/493.js:1:6844)
    at async c (/var/task/.next/server/app/(dashboard)/recordings/page.js:38:14246) {
  digest: '632071067'
}

how i solve this? i have already set the variables

**Comment by abdtriedcoding** [comment]
while setup clerk u also need to add convex template in your clerk auth app. U can refer to youtube video for more on clerk auth with convex.
